In [4]:
import numpy as np

# differece between python list and numpy array: 

# python list:
pyhon_list = [1,2,3,4,5]
print(pyhon_list)

# numpy array:
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [5]:
# One-Dimensional Array (1d Array):

import numpy as np
ar_1d = np.array([10,20,30,40,50])
print(ar_1d)

[10 20 30 40 50]


In [7]:
# Two-Dimensional Array (2d Array):

ar_2d = np.array([[1,2,3],
                 [4,5,6,],
                 [7,8,9]])
print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Multi-Dimensional Array:
# matrix

matrix= np.array([[2,4,6],
                 [8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


# Creating Array's From Python Lists

In [2]:
import numpy as np

# syntax :
# np.array([Element1,Element2,Element3,])   we can pass multiple elements in that list

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [11]:
# With Default Values
# syntax :

# np.zeros(shape) Shape means what is size of your array

zoros_array = np.zeros(3)
print(zoros_array)

[0. 0. 0.]


In [9]:
# When we want all values 1
# syntax :

# np.ones(shape)
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# When we want specific value, (not want 1 / not want want 0)
# syntax : 
# np.full((rows, column), value)

filled_array = np.full((2,3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]]


# Creating sequences of number in numpy

In [31]:
# arange()  It is function it return numpy array
# syntax :
# arange(start, stop, step)

import numpy as np

arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [35]:
# creating identity matrix
# np.eye(size)  It is also function

i_matrix = np.eye(4)
print(i_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
