# Delete / Removing:
- It used to removing the element from array

- Using Delete Function

### Synntax:
- **np.delete(array, index_number, axis = None)**

In [7]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

new_arr = np.delete(arr, 1, axis=0)

In [13]:
print('First Array:')
print(arr)

print('\nNew array:')
print(new_arr)

First Array:
[10 20 30 40 50 60]

New array:
[10 30 40 50 60]


**20 Is Deleted From Array**

# Delete / Removing In Multi-Dimensional Array
- It means direct deleting row / column
- **axis = 0** : It means deleting row.
- **axis = 1** : It means deleting column.

In [19]:
arr_2d = np.array([[1,2,3],[4,5,6]])

new_arr_2d = np.delete(arr_2d, 0, axis = 0)

In [20]:
print(new_arr_2d)

[[4 5 6]]
