## Indexing & Slicing
- Using Indexing & Slicing We Can Access Any Element From Array

- **Indexing:** It means selecting single element From any array, In Indexing We Can Selecting Single Element

- **Slicing:** In slicing we can pick / select multiple elements from any array

## 1.Fancy Indexing
## 2.Boolean Masking / (Filtering Data)

- **Fancy Indexing:** Used to selecting multiple elements at one time, using list of indices.
- **Boolean Masking:** It used bby giving conditions to pick elements from array.

In [2]:
import numpy as np

### Access specific element in the array
**syntax**

- array[index_number] # used on 1d array

- array[row, column] # used on 2d / multi array

In [3]:
# Indixing :

arr = np.array([10,20,30,40,50])
print(arr[0])  # first element
print(arr[2])  # answer becomes 30 because it starts from 0 index
print(arr[-1]) # To print last element

10
30
50


## Slicing :
#### syntax:
- array[start:stop:step]



In [4]:
arr = np.array([10,20,30,40,50])
print(arr[0:4])
print(arr[:4])

print('*'*10)
print(arr[0:5:2])
print(arr[::2])
print('*'*10)

print(arr[::-1])

[10 20 30 40]
[10 20 30 40]
**********
[10 30 50]
[10 30 50]
**********
[50 40 30 20 10]


## Fancy Indexing
- selecting multiple elements at once
- we can select any element at a time 

In [5]:
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])
print(arr[[0,4,3]])

[10 30 50]
[10 50 40]


## Boolean Masking Filtering Data

In [6]:
arr = np.array([10,20,30,40,50])
print(arr[arr > 20])

[30 40 50]
