# Syntax: 
**np.insert(array, index_number, value, axis = None)**

- **array** = original array.
- **index** = position where you want insert value.
- **value** = It means that actual data.
- **axis** = if it is none the it is inserted into a flatten direct

## With 2d-Array:
- **axis = 0:** It means row-wise data insert
- **axis = 1:** It means column-wise data insert

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

new_arr = np.insert(arr, 2, 100)
print(arr)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


- **Insert in 2d-Array**

In [4]:

# Array
arr_2d = np.array([[1,2,], [3,4]])

# insert a new row at index 1
new_arr_2d = np.insert(arr_2d, 1,[5,6], axis = 0)

print('Added Value OR Element BY row-wise')
print(new_arr_2d)
print('*'* 30)

new_flatten_arr_2d = np.insert(arr_2d, 1,[5,6], axis = None)
print('Added Valu OR element flatten')
print(new_flatten_arr_2d)

Added Value OR Element BY row-wise
[[1 2]
 [5 6]
 [3 4]]
******************************
Added Valu OR element flatten
[1 5 6 2 3 4]
