### Mathamatical Operations Without using loops

In [2]:
import numpy as np

In [17]:
arr = np.array([10,20,30])

print(f'Added 5 In All Values: {arr + 5}')
print(f'Multiply all values by 2 : {arr * 2}')
print(f'All Values Squre: {arr ** 2}')

Added 5 In All Values: [15 25 35]
Multiply all values by 2 : [20 40 60]
All Values Squre: [100 400 900]


In [16]:
new_arr = arr - 2

In [13]:
print(new_arr)

[ 8 18 28]


In [14]:
arr

array([10, 20, 30])

In [15]:
new_arr

array([ 8, 18, 28])