## Reshaping
- Changing dimension of array without modifying data **(Dimension -- Shape)**
- E.g.  1d-array into 2d-array / 2d-array into 3d-array  **without changing data**
- using:  
**arr.reshape()**

### Syntax:

#### reshape(rows, columns)
- **if dimensions match**
- **Reshaping dose not create copy, It returns view**

In [29]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

reshape_arr = arr.reshape(3,2,2)
print(reshape_arr)
print(f'{reshape_arr.ndim}D Array')

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3D Array


## - Flattening Arrays

- It used to convert multi-dimensional array into one-dimensional array

- **Flatten**
- **.ravel():** It returns a view.
- **.flatten():** It returns a copy.

In [32]:
arr_2d  = np.array([[1,2,3],[3,4,5]])

arr2 = arr_2d.ravel()
arr = arr_2d.flatten()

In [37]:
print(f'{arr2.ndim}D Array')

1D Array


In [36]:
print(f'{arr.ndim}D Array')

1D Array
