# Staking
- It is used to combine large amount of arrays vertically or horizontaly
- Used to merging arrays vertically / horizontaly
- - --
- **There are two functions:**
- 1. **vstack() :** used for row-wise
- 2. **hstack() :** used for column-wise

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

print('Vertically Row-Wise')
print(np.vstack((arr1, arr2)))

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
print('Horizontaly column-Wise')

print(np.hstack((arr1, arr2)))

Horizontaly column-Wise
[1 2 3 4 5 6 7 8]


# Spliting
- I means divding main array into sub-parts
- **there are three functions**

- **1. np.split() :** used to devide any array in equal part
- **2. np.hsplit() :** used to devide any array horizontally
- **3. np.vsplit() :** used to devide any array ertically
- **np.vsplit()** is used to split a 2D (or higher-dimensional) array vertically (row-wise).

- devide means spliting

In [6]:
import numpy as np

In [36]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])

print(np.split(arr, 1))

[array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])]


In [32]:
print(np.vsplit(arr, 2))

[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]])]


In [42]:
print(np.hsplit(arr,1))

[array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])]
